import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { CartProvider } from './context/CartContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=""  style={{
      backgroundImage: "url('/image1.png')",
    }}>
        <Header></Header>
        <div className="pt-24 pb-5">
          <CartProvider>
            {children}
          </CartProvider>
          
        </div>
      </body>
    </html>
  );
}
